services:
  - type: web
    name: wavelength
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'"